name: Build and Test

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Cache NuGets
      uses: actions/cache@v2
      with:
        path: ~/.nuget/packages
        # Look to see if there is a cache hit for the corresponding requirements file
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget
    - name: Restore dependencies
      run: dotnet restore BddPatterns.sln
    - name: Build
      run: dotnet build --no-restore BddPatterns.sln
    - name: Test
      run: dotnet test --no-build --verbosity normal BddPatterns.sln
      # github.head_ref is only set for PRs
    - name: Generate living docs
      if: ${{success() && github.head_ref != null}}
      run: |
        dotnet tool install --global specflow.plus.livingdoc.cli
        cd tests/Books.Spec/bin/Debug/net5.0/
        livingdoc test-assembly ./Books.Spec.dll -t TestExecution.json
    - name: Upload Living Docs to GitHub
      if: ${{success() && github.head_ref != null}}
      uses: actions/upload-artifact@v2.2.2
      with:
        name: ${{format('{0}-TestResults', github.head_ref)}}
        path: tests/Books.Spec/bin/Debug/net5.0/LivingDoc.html
        retention-days: 7
